export const DASHBOARD_VIEW_KEYS = [
  "brand",
  "users",
  "events",
  "subscribers",
  "attributes",
  "integrations",
  "asset-library",
  "studio",
  "catalog",
  "feeds",
  "journeys",
  "experiences",
  "accounts",
  "deals",
  "tasks",
  "meetings",
  "scheduler",
  "out-of-the-box",
  "boards",
  "subscription",
  "recipes",
] as const;
