export const DASHBOARD_VIEW_KEYS = [
  "brand",
  "users",
  "events",
  "subscribers",
  "connections",
  "asset-library",
  "avatars",
  "scenes",
  "poses",
  "design-system",
  "catalog",
  "feeds",
  "journeys",
  "experiences",
  "accounts",
  "deals",
  "meetings",
  "scheduler",
  "out-of-the-box",
  "boards",
  "subscription",
] as const;
